FROM python:3.7.7

ENV http_proxy http://proxy.olympus.co.jp:8080
ENV https_proxy http://proxy.olympus.co.jp:8080
ENV DIR /root

WORKDIR ${DIR}

RUN pip install \
    --index-url  http://10.155.47.34/ipf3-offshore/pypi/ \
    --trusted-host 10.155.47.34 \
    mantis_soap \
    elasticsearch==7.9.1

ADD insert_and_update_ticket.sh ${DIR}
ADD insert_es.py ${DIR}

ENTRYPOINT ["/root/insert_and_update_ticket.sh"]
