version: '3'

services:

  web:
    container_name: searchapp-web
    image: searchapp-web:latest
    ports:
      - "8088:8080"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - app

  app:
    container_name: searchapp
    image: searchapp
    ports:
      - "8090:8000"
    depends_on:
      - es

  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    restart: always
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
